# Generated by Django 4.2.14 on 2024-08-04 07:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the book', max_length=255)),
                ('author', models.CharField(help_text='Author of the book', max_length=255)),
                ('genre', models.CharField(help_text='Genre of the book', max_length=100)),
                ('rating', models.FloatField(help_text='Average rating of the book (0.0 to 5.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('publication_date', models.DateTimeField(auto_now_add=True, help_text='Date the book was published')),
                ('published_by', models.ForeignKey(help_text='Date and time when the recommendation was created', on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False, help_text='Whether the user liked the recommendation')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the recommendation was created')),
                ('book', models.ForeignKey(help_text='The recommended book', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='book.book')),
                ('user', models.ForeignKey(help_text='User interacting with the recommendation', on_delete=django.db.models.deletion.CASCADE, related_name='user_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('book', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Content of the comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the comment was created')),
                ('recommendation', models.ForeignKey(help_text='The book being commented on', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='book.recommendation')),
                ('user', models.ForeignKey(help_text='User who made the comment', on_delete=django.db.models.deletion.CASCADE, related_name='book_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title', 'author'], name='book_book_title_02eae5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'author')},
        ),
    ]
